CREATE TABLE user (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id VARCHAR(20) NOT NULL,
    password VARCHAR(255) NOT NULL,
    name VARCHAR(10) NOT NULL,
    role VARCHAR(10) NOT NULL,
    date DATETIME
);